### ISSUE TITLE
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gconst02** [gfairchild/yelpapi#5] opened 2017-05-12 00:42 UTC
```
 File "/usr/local/lib/python3.4/dist-packages/yelpapi/yelpapi.py", line 71, in search_query
    return self._query(SEARCH_API_URL, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/yelpapi/yelpapi.py", line 147, in _query
    response_json = response.json() # it shouldn't happen, but this will raise a ValueError if the response isn't JSON
  File "/usr/lib/python3/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.4/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.4/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by gfairchild** [comment] 2017-05-12 03:43
Ummm...ok. Mind providing a little more information?

**Comment by gconst02** [comment] 2017-05-12 07:46
I wish I had more... I basically call search_query in a while loop with options:
```
search_query(latitude=lat, longitude=lon, radius=radius, sort_by='distance', offset=offset, limit=40)
```
It works perfectly for most of the time and then at some point I get this exception. I guess the response fails to be loaded as JSON. Also this is not related to API limit because when I handle the exception I can keep sending requests successfully.

**Comment by gfairchild** [comment] 2017-05-12 13:59
Ok cool, I'll look into it, but unfortunately, it probably won't be until next week. I'm on vacation until Wednesday.

**Comment by gconst02** [comment] 2017-05-12 20:59
No problem! Thanks for maintaining this client

**Comment by gfairchild** [comment] 2017-10-19 01:57
@gconst02, are you still experiencing this issue? I just tried to reproduce it without success:

```
yelp_api.search_query(latitude=35.880036, longitude=-106.303114, radius=20, sort_by='distance', offset=0, limit=40)
```

This works.

If you're still experiencing this issue, I need a minimal working example that will allow me to reproduce your error.

**Comment by gfairchild** [comment] 2018-01-28 18:53
@gconst02, I'm going to go ahead and close this issue since I can't reproduce it without a minimal working example. If you continue to experience this issue, please reopen it and provide a minimal working example.

**Closed by gfairchild** 2018-01-28 18:53 UTC
